esphome:
  name: 5v1c-relay

esp8266:
  board: sonoff_basic

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:


binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "Relay"
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: no

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
web_server:
  port: 80
  version: 2
  auth:
    username: admin
    password: !secret web_server_password
