esphome:
  name: esp32-garage

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


sensor:

  - platform: dht
    pin: 14
    model: AM2302
    temperature:
      name: "Living Room Temperature"
    humidity:
      name: "Living Room Humidity"
    update_interval: 30s

  - platform: dht
    pin: 15
    model: AM2302
    temperature:
      name: "Garage Temperature"
    humidity: 
      name: "Garage Humidity"
      filters:
      - offset: -10
    update_interval: 30s
    
binary_sensor:
  - platform: gpio
    pin: 
      number: 12
      mode: 
        pullup: true
        input: true
    name: "Garage Door"
    device_class: garage_door
    
web_server:
  port: 80
  version: 2
  auth:
    username: admin
    password: !secret web_server_password
    
