esphome:
  name: esp32-1

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: arduino

# Enable logging
logger:


i2c:
    sda: 21
    scl: 22
    scan: true


sensor:

  - platform: bmp280
    address: 0x76
    temperature:
      name: "BME280 Temperature"
      oversampling: 16x
    pressure:
      name: "BME280 Pressure"
      filters:
      - calibrate_linear:
          # Map 0.0 (from sensor) to 0.0 (true value)
          - 0.0 -> 0.0
          - 940 -> 1010
    update_interval: 30s

  - platform: ct_clamp
    sensor: adc_sensor
    name: "My Current Sensor PC"
    id: measured_current
    update_interval: 10s
    filters:
      - calibrate_linear:
          # Measured value of 0 maps to 0A
          - 0.002 -> 0
          # Known load: 4.0A
          # Value shown in logs: 0.1333A
          - 0.126 -> 9.56

    
  - platform: adc
    pin: 35
    id: adc_sensor
    update_interval: 5s
    attenuation: 11db
    
  - platform: template
    id: my_power
    name: "Measured Power PC"
    lambda: return id(measured_current).state * 230.0 ; #Power = Current * Voltage (so change 230 to whatever your mains voltage is)
    unit_of_measurement: 'W'
    update_interval: 5s

  - platform: total_daily_energy
    name: "Total Daily Energy PC"
    power_id: my_power

  - platform: dht
    pin: 15
    model: AM2302
    temperature:
      name: "Outside Temperature"
    humidity:
      name: "Outside Humidity"
      filters:
      - offset: -10
    update_interval: 30s

    
binary_sensor:

  - platform: gpio
    filters:
      - invert:
      - delayed_on_off: 2000ms
    pin:
      number: 2
      mode:
        pullup: true
        input: true
    name: "Rain"
    device_class: moisture
  
time:
  - platform: sntp
    id: my_time

# Enable Home Assistant API
api:

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

web_server:
  port: 80
  version: 2
  auth:
    username: admin
    password: !secret web_server_password
