esphome:
  name: sonoff-2

esp8266:
  board: sonoff_th

# Enable logging
logger:


# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Sonoof-2 Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "Sonoof-2 Relay"
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: no
    
sensor:
  platform: dht
  pin: 
    number: 14
    mode: INPUT_PULLUP
  model: AM2302
  temperature:
     name: "Sonoof-2 Temperature"
  humidity:
     name: "Sonoof-2 Humidity"
  update_interval: 10s
  
web_server:
  port: 80
  version: 2
  auth:
    username: admin
    password: !secret web_server_password
